### ISSUE TITLE
SshProxy.close() on tunnelled SSH connection not closing connection on gateway

### ISSUE THREAD

**Issue by JawaGL** [parmentelat/apssh#10]
When connecting to 2 nodes behind a gateway, apssh first create 2 connection to the gateway before connecting to the initial target. Which means that we have a SSH connection to the gateway per node behind it. These connections remain until the end of the python script instead of being kill when we close the 2nd hop distant proxy (which in `nepi-ng` is done by calling manually shudown() on the main scheduler).

## Cause  :
The `_close_ssh()` method only call the `close()` method of its connection and never call the one of its gateway. 

Moreover, the `_connect_direct()` function works like : 
```
self.conn, _ = [...](asyncssh.create_connection([...]),[...])
```

This mean that each time a node will try to connect its gateway, the parameter `self.conn` will be overwritten with a new connection.

## Possible fix :

We cannot just call `self.gateway.close()` since the stored connection is maybe not the good one.

We can store all gateway connections but we would need a way to pair them with the second hop that has created it. 

Or we can simply make the `_connect_direct()` return its newly created connection and store it in the second hop node. Then when we want to close the connection on the said node we just have to also close this stored gateway connection : [example](https://github.com/JawaGL/apssh/commit/f55cfc6b5d8fb0c4f799e623e46f32ba9ec006bf#diff-5b642b96054a3fba7b832eabefc1085c "Modification on a fork on github").

**Comment by parmentelat** [comment]
In 0.13.0:
* ssh-connections may be explicitly closed by the caller, using `apssh.close_ssh_in_scheduler()`
* no implicit/automatic mechanism tries to tear down an ssh connection
