### ISSUE TITLE
os.getlogin() doesnt work

### ISSUE THREAD

**Issue by manickaraja** [parmentelat/apssh#12]
Hi,
 We are using below command to get the original login user. In some cases folks sudo as different user and run commands. In some cases folks use switch to different user (su - <<user>>) and then run command. In all cases we would like to get original user who logged into the terminal to run the command. We are using below command to get the same.

 user=os.getlogin()

We got three RHEL linux systems with Python 3  and strangely on two of them this command works fine. However only on third system it is failing with below error

OSError: [Errno 6] No such device or address

 Not sure if it is some o/s env setup which is causing this command to fail. Any pointers to run this command will be of great help so that we can pin point the issue.

Please note on faiing system if I do python and then run the command it works fine without any issue. However if it is triggered through our Scheduler (Control M) it is failing with above message.

Give below is the command how Scheduler triggers the job.

/bin/su - edwadm -c  /bin/sh -x <<command to run>>

Thanks
Manick.

**Comment by parmentelat** [comment]
a quick goggle fished for this 
👍 https://www.gitmemory.com/issue/dblossom-marist/PerfMon/20/508160526

but can you please first elaborate on how this relates to apssh ? 
I can see that I use it to figure the default user, is that your problem ?

it'd be easy enough to try other approaches when getlogin() fails;  like e.g. env. variables LOGNAME or USER as suggested is the referenced blog, and I'd welcome a PR to that effect if that's an impediment for you

**Comment by manickaraja** [comment]
I am sorry. I just realized I logged against wrong branch. It is not related to apssh. You may close if you wish. However just to answer your suggestion both LOGNAME and USER gives current sudo'ed user but not original user. For instance, if I login to linux host as my user name (manick) and sudo to another service account(edwadm), both LOGNAME & USER gives edwadm where as I want to capture "manick"
